   var pokemons = [
        {name:"妙蛙種子", nationalNo:1},
{name:"妙蛙草", nationalNo:2},
{name:"妙蛙花", nationalNo:3},
{name:"小火龍", nationalNo:4},
{name:"火恐龍", nationalNo:5},
{name:"噴火龍", nationalNo:6},
{name:"傑尼龜", nationalNo:7},
{name:"卡咪龜", nationalNo:8},
{name:"水箭龜", nationalNo:9},
{name:"綠毛蟲", nationalNo:10},
{name:"鐵甲蛹", nationalNo:11},
{name:"巴大蝶", nationalNo:12},
 {name:"獨角蟲", nationalNo:13},
{name:"鐵殼蛹", nationalNo:14},
{name:"大針蜂", nationalNo:15},
{name:"波波", nationalNo:16},
{name:"比比鳥", nationalNo:17},
{name:"大比鳥", nationalNo:18},
{name:"小拉達", nationalNo:19},
{name:"拉達", nationalNo:20},
{name:"烈雀", nationalNo:21},
{name:"大嘴雀", nationalNo:22},
{name:"阿柏蛇", nationalNo:23},
{name:"阿柏怪", nationalNo:24},
{ name: "皮卡丘", nationalNo: 25 },
{ name: "雷丘", nationalNo: 26 },
{ name: "穿山鼠", nationalNo: 27 },
{ name: "穿山王", nationalNo: 28 },
{ name: "尼多蘭", nationalNo: 29 },
{ name: "尼多娜", nationalNo: 30 },
{ name: "妮多后", nationalNo: 31 },
{ name: "尼多朗", nationalNo: 32 },
{ name: "尼多利諾", nationalNo: 33 },
{ name: "尼多王", nationalNo: 34 },
{ name: "皮皮", nationalNo: 35 },
{ name: "皮可西", nationalNo: 36 },
{ name: "六尾", nationalNo: 37 },
{ name: "九尾", nationalNo: 38 },
{ name: "胖丁", nationalNo: 39 },
{ name: "胖可丁", nationalNo: 40 },
{ name: "超音蝠", nationalNo: 41 },
{ name: "大嘴蝠", nationalNo: 42 },
{ name: "走路草", nationalNo: 43 },
{ name: "臭臭花", nationalNo: 44 },
{ name: "霸王花", nationalNo: 45 },
{ name: "派拉斯", nationalNo: 46 },
{ name: "派拉斯特", nationalNo: 47 },
{ name: "毛球", nationalNo: 48 },
{ name: "摩魯蛾", nationalNo: 49 },
{ name: "地鼠", nationalNo: 50 },
{ name: "三地鼠", nationalNo: 51 },
{ name: "喵喵", nationalNo: 52 },
{ name: "貓老大", nationalNo: 53 },
{ name: "可達鴨", nationalNo: 54 },
{ name: "哥達鴨", nationalNo: 55 },
{ name: "猴怪", nationalNo: 56 },
{ name: "火爆猴", nationalNo: 57 },
{ name: "卡蒂狗", nationalNo: 58 },
{ name: "風速狗", nationalNo: 59 },
{ name: "蚊香蝌蚪", nationalNo: 60 },
{name:"蚊香君", nationalNo:61},
{name:"蚊香泳士", nationalNo:62},
{name:"凱西", nationalNo:63},
{name:"勇基拉", nationalNo:64},
{name:"胡地", nationalNo:65},
{name:"腕力", nationalNo:66},
{name:"豪力", nationalNo:67},
{name:"怪力", nationalNo:68},
{name:"喇叭芽", nationalNo:69},
{name:"口呆花", nationalNo:70},
{name:"大食花", nationalNo:71},
{name:"瑪瑙水母", nationalNo:72},
{name:"毒刺水母", nationalNo:73},
{name:"小拳石", nationalNo:74},
{name:"隆隆石", nationalNo:75},
{name:"隆隆岩", nationalNo:76},
{name:"小火馬", nationalNo:77},
{name:"烈焰馬", nationalNo:78},
{name:"呆呆獸", nationalNo:79},
{name:"呆殼獸", nationalNo:80},
{name:"小磁怪*", nationalNo:81},
{name:"三合一磁怪*", nationalNo:82},
{name:"大蔥鴨", nationalNo:83},
{name:"嘟嘟", nationalNo:84},
{name:"嘟嘟利", nationalNo:85},
{name:"小海獅", nationalNo:86},
{name:"白海獅", nationalNo:87},
{name:"臭泥", nationalNo:88},
{name:"臭臭泥", nationalNo:89},
{name:"大舌貝", nationalNo:90},
{name:"刺甲貝", nationalNo:91},
{name:"鬼斯", nationalNo:92},
{name:"鬼斯通", nationalNo:93},
{name:"耿鬼", nationalNo:94},
{name:"大岩蛇", nationalNo:95},
{name:"催眠貘", nationalNo:96},
{name:"引夢貘人", nationalNo:97},
{name:"大鉗蟹", nationalNo:98},
{name:"巨鉗蟹", nationalNo:99},
{name:"霹靂電球", nationalNo:100},
{name:"頑皮雷彈", nationalNo:101},
{name:"蛋蛋", nationalNo:102},
{name:"椰蛋樹", nationalNo:103},
{name:"卡拉卡拉", nationalNo:104},
{name:"嘎啦嘎啦", nationalNo:105},
{name:"飛腿郎", nationalNo:106},
{name:"快拳郎", nationalNo:107},
{name:"大舌頭", nationalNo:108},
{name:"瓦斯彈", nationalNo:109},
{name:"雙彈瓦斯", nationalNo:110},
{name:"獨角犀牛", nationalNo:111},
{name:"鑽角犀獸", nationalNo:112},
{name:"吉利蛋", nationalNo:113},
{name:"蔓藤怪", nationalNo:114},
{name:"袋獸", nationalNo:115},
{name:"墨海馬", nationalNo:116},
{name:"海刺龍", nationalNo:117},
{name:"角金魚", nationalNo:118},
{name:"金魚王", nationalNo:119},
{name:"海星星", nationalNo:120},
{name:"寶石海星", nationalNo:121},
{name:"魔牆人偶*", nationalNo:122},
{name:"飛天螳螂", nationalNo:123},
{name:"迷唇姐", nationalNo:124},
{name:"電擊獸", nationalNo:125},
{name:"鴨嘴火獸", nationalNo:126},
{name:"凱羅斯", nationalNo:127},
{name:"肯泰羅", nationalNo:128},
{name:"鯉魚王", nationalNo:129},
{name:"暴鯉龍", nationalNo:130},
{name:"拉普拉斯", nationalNo:131},
{name:"百變怪", nationalNo:132},
{name:"伊布", nationalNo:133},
{name:"水伊布", nationalNo:134},
{name:"雷伊布", nationalNo:135},
{name:"火伊布", nationalNo:136},
{name:"多邊獸", nationalNo:137},
{name:"菊石獸", nationalNo:138},
{name:"多刺菊石獸", nationalNo:139},
{name:"化石盔", nationalNo:140},
{name:"鐮刀盔", nationalNo:141},
{name:"化石翼龍", nationalNo:142},
{name:"卡比獸", nationalNo:143},
{name:"急凍鳥", nationalNo:144},
{name:"閃電鳥", nationalNo:145},
{name:"火焰鳥", nationalNo:146},
{name:"迷你龍", nationalNo:147},
{name:"哈克龍", nationalNo:148},
{name:"快龍", nationalNo:149},
{name:"超夢", nationalNo:150},
{name:"夢幻", nationalNo:151},
    ];

module.exports=pokemons;
      